name: appainter
description: A material theme editor and generator for Flutter to configure and
  preview the overall visual theme of your material app.
publish_to: "none"
version: 1.7.2-next+6

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: 3.10.0

dependencies:
  appainter_annotations:
    path: packages/annotations
  bloc: 8.1.2
  collection: 1.17.1
  copy_with_extension: 5.0.3
  cupertino_icons: 1.0.5
  device_preview: 1.1.0
  dio: 5.2.1+1
  dropdown_search: 5.0.6
  enum_to_string: 2.0.1
  equatable: 2.0.5
  expandable: 5.0.1
  file_picker: 5.3.2
  firebase_analytics: 10.4.3
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  flex_color_picker: 3.2.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_markdown: 0.6.15
  google_fonts: 5.1.0
  intl: 0.18.1
  json_theme: 6.0.1
  material_color_utilities: 0.2.0
  material_design_icons_flutter: 7.0.7296
  ndialog: 4.3.0
  path_provider: 2.0.15
  pretty_json: 2.0.0
  random_color_scheme: 0.1.4
  sentry_flutter: 7.8.0
  shared_preferences: 2.2.0
  universal_html: 2.2.3
  universal_io: 2.2.2
  url_launcher: 6.1.11
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 89c350f787e1d7bff12b3517e5671146211ee70e
dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  appainter_builder:
    path: packages/builder
  bloc_test: 9.1.3
  build_runner: 2.4.6
  cider: 0.2.3
  copy_with_extension_gen: 5.0.3
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  remove_from_coverage: 2.0.0
  sentry_dart_plugin: 1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

sentry:
  upload_native_symbols: true
  upload_source_maps: true
  include_native_sources: true
  commits: false
