name: appainter
description: A material theme editor and generator for Flutter to configure and
  preview the overall visual theme of your material app.
publish_to: "none"
version: 1.9.5-next+16

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.8

dependencies:
  appainter_annotations:
    path: packages/annotations
  bloc: 8.1.2
  collection: ^1.17.2
  copy_with_extension: 5.0.4
  cupertino_icons: 1.0.6
  device_preview: 1.1.0
  dio: 5.3.3
  dropdown_search: 5.0.6
  enum_to_string: 2.0.1
  equatable: 2.0.5
  expandable: 5.0.1
  file_picker: 6.0.0
  firebase_analytics: 10.4.5
  firebase_auth: 4.9.0
  firebase_core: 2.15.1
  flex_color_picker: 3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_markdown: 0.6.18
  google_fonts: 6.1.0
  intl: 0.18.1
  json_theme: 6.3.0
  material_color_utilities: ^0.5.0
  material_design_icons_flutter: 7.0.7296
  ndialog: 4.3.1
  path_provider: 2.1.1
  pretty_json: 2.0.0
  random_color_scheme: 0.1.4
  sentry_flutter: 7.11.0
  shared_preferences: 2.2.2
  universal_html: 2.2.4
  universal_io: 2.2.2
  url_launcher: 6.1.14
  window_manager: 0.3.7
dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  appainter_builder:
    path: packages/builder
  bloc_test: 9.1.4
  build_runner: 2.4.6
  cider: 0.2.4
  copy_with_extension_gen: 5.0.4
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter
  mocktail: 1.0.1
  path_provider_platform_interface: 2.1.1
  remove_from_coverage: 2.0.0
  sentry_dart_plugin: 1.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

sentry:
  upload_native_symbols: true
  upload_source_maps: true
  include_native_sources: true
  commits: false
