name: appainter
description: A material theme editor and generator for Flutter to configure and
  preview the overall visual theme of your material app
publish_to: "none"
version: 1.15.9

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.6

dependencies:
  appainter_annotations:
    path: packages/annotations
  bloc: 8.1.4
  collection: ^1.17.2
  copy_with_extension: 5.0.4
  cupertino_icons: 1.0.8
  device_preview: 1.1.0
  dio: 5.4.3
  dropdown_search: 5.0.6
  enum_to_string: 2.0.1
  equatable: 2.0.5
  expandable: 5.0.1
  file_picker: 8.0.3
  firebase_analytics: 10.10.4
  firebase_auth: 4.19.4
  firebase_core: 2.30.1
  flex_color_picker: 3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  flutter_markdown: 0.7.1
  google_fonts: 6.2.1
  intl: 0.19.0
  json_theme: 6.4.1
  material_color_utilities: ^0.8.0
  material_design_icons_flutter: 7.0.7296
  ndialog: 4.3.1
  path_provider: 2.1.3
  pretty_json: 2.0.0
  random_color_scheme: 0.1.4
  sentry_flutter: 8.0.0
  shared_preferences: 2.2.3
  universal_html: 2.2.4
  universal_io: 2.2.2
  url_launcher: 6.2.6
  window_manager: 0.3.8
dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  appainter_builder:
    path: packages/builder
  bloc_test: 9.1.7
  build_runner: 2.4.9
  copy_with_extension_gen: 5.0.4
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 1.0.3
  path_provider_platform_interface: 2.1.2
  remove_from_coverage: 2.0.0
  sentry_dart_plugin: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

sentry:
  upload_native_symbols: true
  upload_source_maps: true
  include_native_sources: true
  commits: false
