name: appainter_builder
description: Builder for generating theme documentations
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^6.0.0
  appainter_annotations:
    path: ../annotations/
  build: ^2.2.1
  collection: ^1.17.1
  html: ^0.15.0
  http: ^1.0.0
  source_gen: ^1.2.1
  textwrap: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.8
  build_test: ^2.1.5
  coverage: ^1.2.0
  flutter_lints: ^4.0.0
  mocktail: ^1.0.0
  test: ^1.20.2
