name: appainter_builder
description: Builder for generating theme documentations
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: 10.0.2
  appainter_annotations:
    path: ../annotations/
  build: 4.0.4
  collection: ^1.17.1
  html: ^0.15.0
  http: ^1.0.0
  source_gen: 4.2.0
  textwrap: ^2.0.0

dev_dependencies:
  build_runner: 2.11.1
  build_test: 3.5.7
  coverage: 1.15.0
  flutter_lints: 6.0.0
  mocktail: 1.0.4
  test: 1.29.0
