name: appainter_builder
description: Builder for generating theme documentations
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  appainter_annotations:
    path: ../annotations/
  build: ^2.2.1
  html: ^0.15.0
  http: ^0.13.4
  source_gen: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.8
  build_test: ^2.1.5
  flutter_lints: ^1.0.4
  mocktail: ^0.3.0
  test: ^1.20.2
