name: Example app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Get project Flutter version ğŸ·ï¸
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Cache Flutter ğŸ’¾
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter ğŸ’»
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Cache build ğŸ’¾
        uses: mikehardy/buildcache-action@v1.2.2
        with:
          cache_key: ${{ runner.os }}-build-example

      - name: Start iOS simulator ğŸ“±
        uses: futureware-tech/simulator-action@v1
        with:
          model: "iPhone 12"

      - name: Run end-to-end tests ğŸ§ª
        run: |
          cd example/
          flutter pub get
          flutter test integration_test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Get project Flutter version ğŸ·ï¸
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Cache Flutter ğŸ’¾
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter ğŸ’»
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Run linting ğŸ§ª
        run: |
          cd example/
          flutter pub get
          flutter analyze
