name: Pull request target actions

on:
  pull_request_target:

jobs:
  pull-request:
    uses: zeshuaro/github-actions-workflows/.github/workflows/pull-request-target.yml@f708c49fc2c7362c69150dbe1acd1868ec30d4d4
